### ISSUE TITLE
Cannot build on Linux: FileType function is not available

### ISSUE THREAD

**Issue by shaunirwin** [PAIR-code/facets#182]
Hi, I am trying to use Facets Dive, but receiving the following error when running ```bazel build facets:facets_jupyter```:

```
Starting local Bazel server and connecting to it...
ERROR: /home/shaun/repos/facets/facets_overview/common/BUILD:7:1: in tf_web_library rule //facets_overview/common:common: 
Traceback (most recent call last):
	File "/home/shaun/repos/facets/facets_overview/common/BUILD", line 7
		tf_web_library(name = 'common')
	File "/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/external/org_tensorflow_tensorboard/tensorboard/defs/web.bzl", line 130, in _tf_web_library
		deprecated_extract_dts_from_closure_libraries(ctx)
	File "/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/external/org_tensorflow_tensorboard/third_party/clutz.bzl", line 54, in deprecated_extract_dts_from_closure_libraries
		depset(FileType(JS_FILE_TYPE).filter(ct...))
	File "/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/external/org_tensorflow_tensorboard/third_party/clutz.bzl", line 54, in depset
		FileType(JS_FILE_TYPE)
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: Analysis of target '//facets:facets_jupyter' failed; build aborted: Analysis of target '//facets_overview/common:common' failed; build aborted
INFO: Elapsed time: 6.794s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (177 packages loaded, 4329 targets configured)
```
If I run the Quickdraw demo using ```bazel run //facets_dive/demo``` I also receive a similar error:

```
ERROR: /home/shaun/repos/facets/facets_dive/demo/BUILD:8:1: in tf_web_library rule //facets_dive/demo:quickdraw: 
Traceback (most recent call last):
	File "/home/shaun/repos/facets/facets_dive/demo/BUILD", line 8
		tf_web_library(name = 'quickdraw')
	File "/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/external/org_tensorflow_tensorboard/tensorboard/defs/web.bzl", line 130, in _tf_web_library
		deprecated_extract_dts_from_closure_libraries(ctx)
	File "/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/external/org_tensorflow_tensorboard/third_party/clutz.bzl", line 54, in deprecated_extract_dts_from_closure_libraries
		depset(FileType(JS_FILE_TYPE).filter(ct...))
	File "/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/external/org_tensorflow_tensorboard/third_party/clutz.bzl", line 54, in depset
		FileType(JS_FILE_TYPE)
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: Analysis of target '//facets_dive/demo:demo' failed; build aborted: Analysis of target '//facets_dive/demo:quickdraw' failed; build aborted
INFO: Elapsed time: 1.807s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (155 packages loaded, 4171 targets configured)
FAILED: Build did NOT complete successfully (155 packages loaded, 4171 targets configured)
```

If I then use the ```bazel build facets:facets_jupyter --incompatible_disallow_filetype=false``` flag as suggested in the above error message the build completes successfully:

```
INFO: Analysed target //facets:facets_jupyter (177 packages loaded, 4342 targets configured).
INFO: Found 1 target...
Target //facets:facets_jupyter up-to-date:
  bazel-genfiles/facets/facets-jupyter.html
INFO: Elapsed time: 8.198s, Critical Path: 2.48s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

The QuickDraw demo also builds successfully when I run the following command: ```bazel run //facets_dive/demo --incompatible_disallow_filetype=false```:

```
INFO: Analysed target //facets_dive/demo:demo (155 packages loaded, 4173 targets configured).
INFO: Found 1 target...
Target //facets_dive/demo:demo up-to-date:
  bazel-bin/facets_dive/demo/demo.html
INFO: Elapsed time: 2.370s, Critical Path: 0.17s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/shaun/.cache/bazel/_bazel_shaun/f9c0a22ad4dc049c72d75f81ff79a309/execroot/ai_google_pair_facets/bazel-out/host/bin/external/com_google_protobuf/libprotobuf_java.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
May 08, 2019 3:10:39 PM io.bazel.rules.closure.webfiles.server.Metadata$Loader loadMetadataIntoObjectGraph
INFO: Loaded build graph in 163ms
May 08, 2019 3:10:39 PM io.bazel.rules.closure.webfiles.server.WebfilesServer runForever
INFO: 
Closure Rules WebfilesServer
Listening on: http://172.17.0.1:6006/


May 08, 2019 3:11:03 PM io.bazel.rules.closure.http.filter.LoggingFilter handle
INFO: 85 879µs /0:0:0:0:0:0:0:1:49442 404 GET /
May 08, 2019 3:11:04 PM io.bazel.rules.closure.http.filter.LoggingFilter handle
INFO: 5 039µs /0:0:0:0:0:0:0:1:49442 404 GET /favicon.ico
```

However, browsing to **localhost:6006** in Google Chrome shows the following:
![facets_browser_error](https://user-images.githubusercontent.com/4746671/57378348-ddb96200-71a4-11e9-9a8b-6f9a258b860f.png)

I am using Ubuntu 16.04 and have encountered the same issue when using Bazel version 0.24 and 0.25.1 (haven't tried any other versions yet). I am using the current master (git commit 3b636773d3376df7b80983cfe9335411d5dec41e).

Do you perhaps know what may be causing this? Any help would be greatly appreciated!

**Comment by shaunirwin** [comment]
Ah, I see. Thanks very much for the help. It is working perfectly after opening that file.
