### ISSUE TITLE
facets dive demo no longer builds

### ISSUE THREAD

**Issue by rmcloughlin** [PAIR-code/facets#247]
The facets dive demo no longer seems to build.  Here is my best attempt in a Dockerfile:

```Dockerfile
FROM ubuntu:focal

RUN apt-get update && apt install -y apt-transport-https curl git gnupg

RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
RUN mv bazel-archive-keyring.gpg /usr/share/keyrings
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list

RUN apt update && apt install -y bazel

WORKDIR /opt

RUN git clone https://github.com/PAIR-code/facets

WORKDIR /opt/facets

RUN bazel build //facets_dive/demo
```

The result I see is:

```
#13 70.61 WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
#13 70.62 ERROR: An error occurred during the fetch of repository 'net_zlib':
#13 70.62    Traceback (most recent call last):
#13 70.62       File "/root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
#13 70.62               download_info = ctx.download_and_extract(
#13 70.62 Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/net_zlib/temp4907857517448745203/zlib-1.2.11.tar.gz: GET returned 404 Not Found
```

**Comment by jameswex** [comment]
try adding to the WORKSPACE file:

http_archive(
    name = "zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = [
        "https://mirror.bazel.build/zlib.net/zlib-1.2.11.tar.gz",
        "https://zlib.net/zlib-1.2.11.tar.gz",
    ],
)

**Comment by rmcloughlin** [comment]
Doesn't seem to fix it, unfortunately.  After adding that to the WORKSPACE file I still get:

```
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/archive/e9fc4750d427196754bebb0e2e1e38d68893490a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_webtesting/archive/0.2.2.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/github.com/google/protobuf/archive/v3.7.1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://mirror.bazel.build/repo1.maven.org/maven2/com/google/template/soy/2019-03-11/soy-2019-03-11.jar failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Repository net_zlib instantiated at:
  /opt/facets/WORKSPACE:57:21: in <toplevel>
  /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/io_bazel_rules_closure/closure/repositories.bzl:175:13: in closure_repositories
  /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/io_bazel_rules_closure/closure/repositories.bzl:1001:17: in zlib
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
WARNING: Download from https://zlib.net/zlib-1.2.11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: An error occurred during the fetch of repository 'net_zlib':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/net_zlib/temp7042427168180112346/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: /opt/facets/WORKSPACE:57:21: fetching http_archive rule //external:net_zlib: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/net_zlib/temp7042427168180112346/zlib-1.2.11.tar.gz: GET returned 404 Not Found
INFO: Repository remote_java_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:363:6: in <toplevel>
  /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /opt/facets/WORKSPACE:57:21: //external:zlib depends on @net_zlib//:zlib in repository @net_zlib which failed to fetch. no such package '@net_zlib//': java.io.IOException: Error downloading [https://zlib.net/zlib-1.2.11.tar.gz] to /root/.cache/bazel/_bazel_root/f0edbeac36261ac6bdca9830d0450fbe/external/net_zlib/temp7042427168180112346/zlib-1.2.11.tar.gz: GET returned 404 Not Found
ERROR: Analysis of target '//facets_dive/demo:demo' failed; build aborted:
INFO: Elapsed time: 44.528s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (155 packages loaded, 4038 targets configured)
    Fetching https://mirror.bazel.build/bazel_java_tools/releases/java/v11.9/java_tools-v11.9.zip; 26.1 MiB (27,385,648B)
```

I tried removing `https://zlib.net/zlib-1.2.11.tar.gz` from the `urls` section because it's a 404 but that didn't work either.

**Comment by avilella** [comment]
Has this been addressed? I would like to build facets_dive for Ubuntu 22.04 or Ubuntu 24.04. Thanks

**Comment by jameswex** [comment]
Sorry, Facets is not an actively supported project so updates to it should not be expected.

One recommendation is to check out https://pair-code.github.io/lit/ which includes a facets-dive-like visualization as part of its suite of things it can do.
