### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'facets-dist/'

### ISSUE THREAD

**Issue by ganesh3** [PAIR-code/facets#90]
(D:\Anaconda3\envs\pythonREnv) C:\Users\ganes>jupyter nbextension install facets-dist/
Copying: facets-dist/ -> C:\ProgramData\jupyter\nbextensions\facets-dist
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pythonREnv\Scripts\jupyter-nbextension-script.py", line 5, in <module>
    sys.exit(notebook.nbextensions.main())
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\notebook\nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\jupyter_core\application.py", line 256, in start
    self.subapp.start()
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\notebook\nbextensions.py", line 678, in start
    self.install_extensions()
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\notebook\nbextensions.py", line 657, in install_extensions
    **kwargs
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\notebook\nbextensions.py", line 199, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "D:\Anaconda3\envs\pythonREnv\lib\site-packages\notebook\nbextensions.py", line 958, in _maybe_copy
    shutil.copy2(src, dest)
  File "D:\Anaconda3\envs\pythonREnv\lib\shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "D:\Anaconda3\envs\pythonREnv\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'facets-dist/'

(D:\Anaconda3\envs\pythonREnv) C:\Users\ganes>

**Comment by jameswex** [comment]
Make sure you are running that command from the base directory of the repository. It looks like perhaps you are running it from your home directory and not the facets base directory.
