### ISSUE TITLE
Bazel Build failed

### ISSUE THREAD

**Issue by ganesh3** [PAIR-code/facets#96]
(D:\Anaconda3\envs\pythonREnv) D:\Anaconda3\share\jupyter\nbextensions\facets-master>bazel build facets:facets_jupyter
.....................
DEBUG: C:/users/ganes/appdata/local/temp/_bazel_ganes/teuucrii/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
DEBUG: C:/users/ganes/appdata/local/temp/_bazel_ganes/teuucrii/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
DEBUG: C:/users/ganes/appdata/local/temp/_bazel_ganes/teuucrii/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:37:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
INFO: Analysed target //facets:facets_jupyter (163 packages loaded).
INFO: Found 1 target...
ERROR: D:/anaconda3/share/jupyter/nbextensions/facets-master/facets_dive/lib/BUILD:29:1: Compiling 4 TypeScript files //facets_dive/lib:data-example failed (Exit 1)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pythonREnv\lib\site.py", line 547, in <module>
    main()
  File "D:\Anaconda3\envs\pythonREnv\lib\site.py", line 542, in main
    os.environ["PATH"])
  File "D:\Anaconda3\envs\pythonREnv\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PATH'
Failed to import the site module
Target //facets:facets_jupyter failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 354.135s, Critical Path: 5.57s
FAILED: Build did NOT complete successfully

**Comment by nehaljwani** [comment]
I had to set `use_default_shell_env = True` in `ctx.action` as documented [here](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#parameters) in another project using bazel to overcome this problem.

**Comment by eggachecat** [comment]
+1

**Comment by eggachecat** [comment]
@ganesh3 hi have you solved this problem?

**Comment by ganesh3** [comment]
Nope.


Regards
Ganesh Bhat
